# Generated by Django 4.2.30 on 2026-06-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号 (Order Number)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额 (Amount)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '订单 (Order)',
                'db_table': 'biz_order',
            },
        ),
    ]
