# Generated by Django 4.2.30 on 2026-06-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EprConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="配置名称 / Configuration Name"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255, verbose_name="配置值 / Configuration Value"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="是否启用 / Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "EPR配置 / EPR Configuration",
                "verbose_name_plural": "EPR配置 / EPR Configuration",
                "db_table": "epr_config",
            },
        ),
    ]
