# Generated by Django 4.2.30 on 2026-06-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '__first__'),
        ('epr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='EPRBatteryChemicalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name_en', models.CharField(max_length=255, unique=True)),
                ('name_cn', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'EPR Battery Chemical Type',
                'verbose_name_plural': 'EPR Battery Chemical Type',
                'db_table': 'epr_battery_chemical_types',
            },
        ),
        migrations.CreateModel(
            name='EPRTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name_en', models.CharField(help_text='name en', max_length=255, unique=True)),
                ('name_cn', models.CharField(help_text='name cn', max_length=255)),
                ('description_en', models.TextField(blank=True, help_text='description en', null=True)),
                ('description_cn', models.TextField(blank=True, help_text='description cn', null=True)),
                ('last_confirmed_date', models.DateField(blank=True, help_text='last confirmed date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='is active')),
            ],
            options={
                'verbose_name': 'EPR Template',
                'verbose_name_plural': 'EPR Template',
                'db_table': 'epr_templates',
                'permissions': [('assign_eprtemplate', 'Can assign products to EPR template')],
            },
        ),
        migrations.CreateModel(
            name='EPRType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name_short_en', models.CharField(help_text='name short en', max_length=50)),
                ('name_short_cn', models.CharField(help_text='name short cn', max_length=50)),
                ('name_en', models.CharField(help_text='name en', max_length=255, unique=True)),
                ('name_cn', models.CharField(help_text='name cn', max_length=255)),
            ],
            options={
                'verbose_name': 'EPR type',
                'verbose_name_plural': 'EPR type',
                'db_table': 'epr_types',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name_en', models.CharField(max_length=255)),
                ('name_cn', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'territory',
            },
        ),
        migrations.CreateModel(
            name='EPRTypesInTerritories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('epr_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_type', to='epr.eprtype', verbose_name='EPR Type')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory', to='epr.territory', verbose_name='Territory')),
            ],
            options={
                'verbose_name': 'EPR Type in Territory',
                'verbose_name_plural': 'EPR Type in Territory',
                'db_table': 'epr_types_in_territories',
                'unique_together': {('territory', 'epr_type')},
            },
        ),
        migrations.CreateModel(
            name='EPRCodeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_defined_by_law', models.BooleanField(default=False, help_text='is defined by law')),
                ('org_name_short', models.CharField(blank=True, help_text='org name short', max_length=100, null=True)),
                ('org_name', models.CharField(blank=True, help_text='org name', max_length=255, null=True)),
                ('type_in_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_sources', to='epr.eprtypesinterritories')),
            ],
            options={
                'verbose_name': 'EPR Code Source',
                'verbose_name_plural': 'EPR Code Source',
                'db_table': 'epr_code_sources',
                'unique_together': {('is_defined_by_law', 'org_name', 'org_name_short', 'type_in_territory')},
            },
        ),
        migrations.CreateModel(
            name='EPRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('code', models.CharField(help_text='code', max_length=255)),
                ('description_en', models.TextField(blank=True, help_text='description en', null=True)),
                ('description_cn', models.TextField(blank=True, help_text='description cn', null=True)),
                ('description_native', models.TextField(blank=True, help_text='description native', null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, help_text='fee', max_digits=10, null=True)),
                ('measuring_unit', models.IntegerField(choices=[(1, 'per_piece'), (2, 'Weight_kg'), (3, 'Volume_m3')], default=1, help_text='measure unit')),
                ('currency', models.ForeignKey(blank=True, help_text='currency', null=True, on_delete=django.db.models.deletion.SET_NULL, to='epr.currency')),
                ('epr_code_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_codes', to='epr.eprcodesource')),
            ],
            options={
                'verbose_name': 'EPR Code',
                'verbose_name_plural': 'EPR Code',
                'db_table': 'epr_codes',
            },
        ),
        migrations.CreateModel(
            name='EPRBatteryProductItemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=3, help_text='Weight in kg, precision 0.001 kg', max_digits=10, verbose_name='Weight (kg)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('battery_chemical_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_item_relations', to='epr.eprbatterychemicaltype', verbose_name='Battery Chemical Type')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battery_chemical_relations', to='products.productitem', verbose_name='Product Item')),
            ],
            options={
                'verbose_name': 'Battery Chemical–Item Relation',
                'verbose_name_plural': 'Battery Chemical–Item Relations',
                'db_table': 'epr_battery_product_item_relations',
                'unique_together': {('battery_chemical_type', 'product_item')},
            },
        ),
        migrations.AddField(
            model_name='eprbatterychemicaltype',
            name='product_items',
            field=models.ManyToManyField(blank=True, related_name='battery_chemical_types', through='epr.EPRBatteryProductItemRelation', to='products.productitem'),
        ),
        migrations.CreateModel(
            name='Territory2EPRTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('weight_override', models.DecimalField(blank=True, decimal_places=6, help_text='weight override', max_digits=10, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_template_links', to='epr.eprcode', verbose_name='Code')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='epr.eprtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Intermediate Table',
                'verbose_name_plural': 'Intermediate Table',
                'db_table': 'epr_territory_templates',
                'unique_together': {('template', 'code')},
            },
        ),
    ]
